@startuml classDiagram

class Book {
    -String ISBN
    -String title
    -String author
    -String genre
    -boolean isAvailable
    +getDetails(): String
    +updateStatus(boolean): void
}

class Member {
    -String memberID
    -String name
    -String email
    -String phoneNumber
    -String password
    -double balance
    +authenticate(String): boolean
    +addFine(double): void 
    +clearBalance(): void
}

class Administrator{
    -String AdministratorID
    -String name
    -String email
    -String password
    +addBook(Book): void
    +editBook(Book): void
    +removeBook(String): void
}

class Transaction {
    -String TransactionID
    -Book book
    -Member member
    -Date issueDate
    -Date dueDate
    +calculateOverdueDays(): int
}

class LibrarySystem {
    -List<Book> books
    -List<Member> members
    -List<Loan> loans
    +searchBook(String): List<Book>
    +processLoan(Member, Book): void
    +processReturn(Loan): void
    +generateReport(): void
}

LibrarySystem "1" *-- "*" Book : manages
LibrarySystem "1" *-- "*" Member : manages
LibrarySystem "1" *-- "*" Transaction : tracks
LibrarySystem "1" *-- "*" Administrator : employs

Transaction "1" .. "1" Book : involves
Transaction "1" .. "1" Member : involves
@enduml